/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AccountSupportRouteImport } from './routes/account/support'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountRewardsRouteImport } from './routes/account/rewards'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountDriversRouteImport } from './routes/account/drivers'
import { Route as AccountDocumentsRouteImport } from './routes/account/documents'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings.index'
import { Route as AccountBookingsIndexRouteImport } from './routes/account/bookings.index'
import { Route as AdminCustomersEmailRouteImport } from './routes/admin/customers.$email'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin/bookings.$bookingId'
import { Route as AccountBookingsBookingIdRouteImport } from './routes/account/bookings.$bookingId'

const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountDriversRoute = AccountDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountDocumentsRoute = AccountDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AccountBookingsIndexRoute = AccountBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountBookingsRoute,
} as any)
const AdminCustomersEmailRoute = AdminCustomersEmailRouteImport.update({
  id: '/$email',
  path: '/$email',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AccountBookingsBookingIdRoute =
  AccountBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => AccountBookingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/documents': typeof AccountDocumentsRoute
  '/account/drivers': typeof AccountDriversRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/bookings/$bookingId': typeof AccountBookingsBookingIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/drivers': typeof AccountDriversRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/bookings/$bookingId': typeof AccountBookingsBookingIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRoute
  '/account/bookings': typeof AccountBookingsIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/account/bookings': typeof AccountBookingsRouteWithChildren
  '/account/documents': typeof AccountDocumentsRoute
  '/account/drivers': typeof AccountDriversRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/bookings/$bookingId': typeof AccountBookingsBookingIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$email': typeof AdminCustomersEmailRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/book'
    | '/account/bookings'
    | '/account/documents'
    | '/account/drivers'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/account/reset-password'
    | '/account/rewards'
    | '/account/settings'
    | '/account/support'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/documents'
    | '/admin/fleet'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/account/bookings/$bookingId'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$email'
    | '/account/bookings/'
    | '/admin/bookings/'
    | '/admin/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/account/documents'
    | '/account/drivers'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/account/reset-password'
    | '/account/rewards'
    | '/account/settings'
    | '/account/support'
    | '/admin/calendar'
    | '/admin/discounts'
    | '/admin/documents'
    | '/admin/fleet'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/account'
    | '/admin'
    | '/account/bookings/$bookingId'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$email'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/customers'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/book'
    | '/account/bookings'
    | '/account/documents'
    | '/account/drivers'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/register'
    | '/account/reset-password'
    | '/account/rewards'
    | '/account/settings'
    | '/account/support'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/documents'
    | '/admin/fleet'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/account/bookings/$bookingId'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$email'
    | '/account/bookings/'
    | '/admin/bookings/'
    | '/admin/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BookRoute: typeof BookRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/drivers': {
      id: '/account/drivers'
      path: '/drivers'
      fullPath: '/account/drivers'
      preLoaderRoute: typeof AccountDriversRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/documents': {
      id: '/account/documents'
      path: '/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof AccountDocumentsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/account/bookings/': {
      id: '/account/bookings/'
      path: '/'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AccountBookingsIndexRouteImport
      parentRoute: typeof AccountBookingsRoute
    }
    '/admin/customers/$email': {
      id: '/admin/customers/$email'
      path: '/$email'
      fullPath: '/admin/customers/$email'
      preLoaderRoute: typeof AdminCustomersEmailRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/account/bookings/$bookingId': {
      id: '/account/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/account/bookings/$bookingId'
      preLoaderRoute: typeof AccountBookingsBookingIdRouteImport
      parentRoute: typeof AccountBookingsRoute
    }
  }
}

interface AccountBookingsRouteChildren {
  AccountBookingsBookingIdRoute: typeof AccountBookingsBookingIdRoute
  AccountBookingsIndexRoute: typeof AccountBookingsIndexRoute
}

const AccountBookingsRouteChildren: AccountBookingsRouteChildren = {
  AccountBookingsBookingIdRoute: AccountBookingsBookingIdRoute,
  AccountBookingsIndexRoute: AccountBookingsIndexRoute,
}

const AccountBookingsRouteWithChildren = AccountBookingsRoute._addFileChildren(
  AccountBookingsRouteChildren,
)

interface AccountRouteRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRouteWithChildren
  AccountDocumentsRoute: typeof AccountDocumentsRoute
  AccountDriversRoute: typeof AccountDriversRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountBookingsRoute: AccountBookingsRouteWithChildren,
  AccountDocumentsRoute: AccountDocumentsRoute,
  AccountDriversRoute: AccountDriversRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminBookingsRouteChildren {
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersEmailRoute: typeof AdminCustomersEmailRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersEmailRoute: AdminCustomersEmailRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BookRoute: BookRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
